### ISSUE TITLE
FishHash algorithm fetch indices misunderstanding

### ISSUE THREAD

**Issue by Grumpy-Dwarf** [iron-fish/fish-hash#4]
In the specification of FishHash algorithm https://github.com/iron-fish/fish-hash/blob/main/FishHash.pdf section 3.2 ReadDataSet subprogram `MixValue` has offsets in bytes: 0, 32,64:

Algorithm 2 ReadDataSet
```
LoadValue[0:127] <- DataSet[MixValue[0:3] % dataSetSize]
LoadValue[128:255] <- DataSet[MixValue[32:35] % dataSetSize]
LoadValue[256:383] <- DataSet[MixValue[64:67] % dataSetSize]
``` 

But in your implementation (both C++ and Rust) they are 0, 16, 32:

https://github.com/iron-fish/fish-hash/blob/dfdd747db0cdbb61a098caa53c5439f79ecea63f/rust/src/lib.rs#L260-L262

https://github.com/iron-fish/fish-hash/blob/dfdd747db0cdbb61a098caa53c5439f79ecea63f/cpp/FishHash.cpp#L147-L149

`sizeof(mix.word32s)` == 4 so we read from `MixValue[0:3]`, `MixValue[16:19]`, `MixValue[32:35]`

Corresponding to Lollidieb's paper indices should be `mix.word32s[0]`, `mix.word32s[8]`, `mix.word32s[16]`.

**Comment by danield9tqh** [comment]
Thank you @Grumpy-Dwarf. At first glance this does seem like a discrepancy between the paper and implementation. We'll look into it 🙏🏻

**Comment by Lolliedieb** [comment]
There indeed was a discrepancy between the cpu implementation and the first iteration of the pdf. The reason is with the original proposal: when the phase with the dag element chasing starts the hash values get replicated from bytes 0..63 to 64..127. Therefore the uint32_t at [0..3] and [64..67] are equal and that leads to a kind of optimization that then gives about 1% higher hashrate, because one needs to fetch the element only ones. But only people who see it can use it and also it makes the code not nice to read, because to use the trick one needs to manually pull out the first loop iteration out of the loop.

Because I did not like this, I decided to go for bytes [0..3], [16..19] and [32..35] instead. The most recent version of the document has this change amended. I will make sure it gets uploaded as soon as possible.
